insert into committee(name) values ('House Agriculture Committee');
insert into committee(name) values ('House Appropriations Committee');
insert into committee(name) values ('House Armed Services Committee');
insert into committee(name) values ('House Budget Committee');
insert into committee(name) values ('House Education and Labor Committee');
insert into committee(name) values ('House Energy and Commerce Committee');
insert into committee(name) values ('House Ethics Committee');
insert into committee(name) values ('House Financial Services Committee');
insert into committee(name) values ('House Foreign Affairs Committee');
insert into committee(name) values ('House Homeland Security Committee');
insert into committee(name) values ('House House Administration Committee');
insert into committee(name) values ('House Intelligence (Permanent Select) Committee');
insert into committee(name) values ('House Judiciary Committee');
insert into committee(name) values ('House Natural Resources Committee');
insert into committee(name) values ('House Oversight and Government Reform Committee');
insert into committee(name) values ('House Rules Committee');
insert into committee(name) values ('House Science, Space, and Technology Committee');
insert into committee(name) values ('House Small Business Committee');
insert into committee(name) values ('House Transportation and Infrastructure Committee');
insert into committee(name) values ('House Veterans Affairs Committee');
insert into committee(name) values ('House Ways and Means Committee');
insert into committee(name) values ('Senate Aging (Special) Committee');
insert into committee(name) values ('Senate Agriculture, Nutrition and Forestry Committee');
insert into committee(name) values ('Senate Appropriations Committee');
insert into committee(name) values ('Senate Armed Services Committee');
insert into committee(name) values ('Senate Banking, Housing, and Urban Affairs Committee');
insert into committee(name) values ('Senate Budget Committee');
insert into committee(name) values ('Senate Commerce, Science and Transportation Committee');
insert into committee(name) values ('Senate Energy and Natural Resources Committee');
insert into committee(name) values ('Senate Ethics (Select) Committee');
insert into committee(name) values ('Senate Environment and Public Works Committee');
insert into committee(name) values ('Senate Finance Committee');
insert into committee(name) values ('Senate Foreign Relations Committee');
insert into committee(name) values ('Senate Health, Education, Labor, and Pensions Committee');
insert into committee(name) values ('Senate Homeland Security and Governmental Affairs Committee');
insert into committee(name) values ('Senate Indian Affairs Committee');
insert into committee(name) values ('Senate Intelligence (Select) Committee');
insert into committee(name) values ('Senate International Narcotics Control (Special) Committee');
insert into committee(name) values ('Senate Judiciary Committee');
insert into committee(name) values ('Senate Rules and Administration Committee');
insert into committee(name) values ('Senate Small Business and Entrepreneurship Committee');
insert into committee(name) values ('Senate Veterans Affairs Committee');
insert into committee values('Joint Economic Committee',  1946);
insert into committee values('Joint Library Committee',  1806);
insert into committee values('Joint Printing Committee',  1846);
insert into committee values('Joint Taxation Committee',  1926);
