insert into district(state, name, chamber) values('Alabama','HR-AL-1','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-2','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-3','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-4','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-5','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-6','House');
insert into district(state, name, chamber) values('Alabama','HR-AL-7','House');
insert into district(state, name, chamber) values('Alaska','HR-AK-AL','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-1','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-2','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-3','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-4','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-5','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-6','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-7','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-8','House');
insert into district(state, name, chamber) values('Arizona','HR-AZ-9','House');
insert into district(state, name, chamber) values('Arkansas','HR-AR-1','House');
insert into district(state, name, chamber) values('Arkansas','HR-AR-2','House');
insert into district(state, name, chamber) values('Arkansas','HR-AR-3','House');
insert into district(state, name, chamber) values('Arkansas','HR-AR-4','House');
insert into district(state, name, chamber) values('California','HR-CA-1','House');
insert into district(state, name, chamber) values('California','HR-CA-2','House');
insert into district(state, name, chamber) values('California','HR-CA-3','House');
insert into district(state, name, chamber) values('California','HR-CA-4','House');
insert into district(state, name, chamber) values('California','HR-CA-5','House');
insert into district(state, name, chamber) values('California','HR-CA-6','House');
insert into district(state, name, chamber) values('California','HR-CA-7','House');
insert into district(state, name, chamber) values('California','HR-CA-8','House');
insert into district(state, name, chamber) values('California','HR-CA-9','House');
insert into district(state, name, chamber) values('California','HR-CA-10','House');
insert into district(state, name, chamber) values('California','HR-CA-11','House');
insert into district(state, name, chamber) values('California','HR-CA-12','House');
insert into district(state, name, chamber) values('California','HR-CA-13','House');
insert into district(state, name, chamber) values('California','HR-CA-14','House');
insert into district(state, name, chamber) values('California','HR-CA-15','House');
insert into district(state, name, chamber) values('California','HR-CA-16','House');
insert into district(state, name, chamber) values('California','HR-CA-17','House');
insert into district(state, name, chamber) values('California','HR-CA-18','House');
insert into district(state, name, chamber) values('California','HR-CA-19','House');
insert into district(state, name, chamber) values('California','HR-CA-20','House');
insert into district(state, name, chamber) values('California','HR-CA-21','House');
insert into district(state, name, chamber) values('California','HR-CA-22','House');
insert into district(state, name, chamber) values('California','HR-CA-23','House');
insert into district(state, name, chamber) values('California','HR-CA-24','House');
insert into district(state, name, chamber) values('California','HR-CA-25','House');
insert into district(state, name, chamber) values('California','HR-CA-26','House');
insert into district(state, name, chamber) values('California','HR-CA-27','House');
insert into district(state, name, chamber) values('California','HR-CA-28','House');
insert into district(state, name, chamber) values('California','HR-CA-29','House');
insert into district(state, name, chamber) values('California','HR-CA-30','House');
insert into district(state, name, chamber) values('California','HR-CA-31','House');
insert into district(state, name, chamber) values('California','HR-CA-32','House');
insert into district(state, name, chamber) values('California','HR-CA-33','House');
insert into district(state, name, chamber) values('California','HR-CA-34','House');
insert into district(state, name, chamber) values('California','HR-CA-35','House');
insert into district(state, name, chamber) values('California','HR-CA-36','House');
insert into district(state, name, chamber) values('California','HR-CA-37','House');
insert into district(state, name, chamber) values('California','HR-CA-38','House');
insert into district(state, name, chamber) values('California','HR-CA-39','House');
insert into district(state, name, chamber) values('California','HR-CA-40','House');
insert into district(state, name, chamber) values('California','HR-CA-41','House');
insert into district(state, name, chamber) values('California','HR-CA-42','House');
insert into district(state, name, chamber) values('California','HR-CA-43','House');
insert into district(state, name, chamber) values('California','HR-CA-44','House');
insert into district(state, name, chamber) values('California','HR-CA-45','House');
insert into district(state, name, chamber) values('California','HR-CA-46','House');
insert into district(state, name, chamber) values('California','HR-CA-47','House');
insert into district(state, name, chamber) values('California','HR-CA-48','House');
insert into district(state, name, chamber) values('California','HR-CA-49','House');
insert into district(state, name, chamber) values('California','HR-CA-50','House');
insert into district(state, name, chamber) values('California','HR-CA-51','House');
insert into district(state, name, chamber) values('California','HR-CA-52','House');
insert into district(state, name, chamber) values('California','HR-CA-53','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-1','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-2','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-3','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-4','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-5','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-6','House');
insert into district(state, name, chamber) values('Colorado','HR-CO-7','House');
insert into district(state, name, chamber) values('Connecticut','HR-CT-1','House');
insert into district(state, name, chamber) values('Connecticut','HR-CT-2','House');
insert into district(state, name, chamber) values('Connecticut','HR-CT-3','House');
insert into district(state, name, chamber) values('Connecticut','HR-CT-4','House');
insert into district(state, name, chamber) values('Connecticut','HR-CT-5','House');
insert into district(state, name, chamber) values('Delaware','HR-DE-AL','House');
insert into district(state, name, chamber) values('Florida','HR-FL-1','House');
insert into district(state, name, chamber) values('Florida','HR-FL-2','House');
insert into district(state, name, chamber) values('Florida','HR-FL-3','House');
insert into district(state, name, chamber) values('Florida','HR-FL-4','House');
insert into district(state, name, chamber) values('Florida','HR-FL-5','House');
insert into district(state, name, chamber) values('Florida','HR-FL-6','House');
insert into district(state, name, chamber) values('Florida','HR-FL-7','House');
insert into district(state, name, chamber) values('Florida','HR-FL-8','House');
insert into district(state, name, chamber) values('Florida','HR-FL-9','House');
insert into district(state, name, chamber) values('Florida','HR-FL-10','House');
insert into district(state, name, chamber) values('Florida','HR-FL-11','House');
insert into district(state, name, chamber) values('Florida','HR-FL-12','House');
insert into district(state, name, chamber) values('Florida','HR-FL-13','House');
insert into district(state, name, chamber) values('Florida','HR-FL-14','House');
insert into district(state, name, chamber) values('Florida','HR-FL-15','House');
insert into district(state, name, chamber) values('Florida','HR-FL-16','House');
insert into district(state, name, chamber) values('Florida','HR-FL-17','House');
insert into district(state, name, chamber) values('Florida','HR-FL-18','House');
insert into district(state, name, chamber) values('Florida','HR-FL-19','House');
insert into district(state, name, chamber) values('Florida','HR-FL-20','House');
insert into district(state, name, chamber) values('Florida','HR-FL-21','House');
insert into district(state, name, chamber) values('Florida','HR-FL-22','House');
insert into district(state, name, chamber) values('Florida','HR-FL-23','House');
insert into district(state, name, chamber) values('Florida','HR-FL-24','House');
insert into district(state, name, chamber) values('Florida','HR-FL-25','House');
insert into district(state, name, chamber) values('Florida','HR-FL-26','House');
insert into district(state, name, chamber) values('Florida','HR-FL-27','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-1','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-2','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-3','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-4','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-5','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-6','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-7','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-8','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-9','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-10','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-11','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-12','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-13','House');
insert into district(state, name, chamber) values('Georgia','HR-GA-14','House');
insert into district(state, name, chamber) values('Hawaii','HR-HI-1','House');
insert into district(state, name, chamber) values('Hawaii','HR-HI-2','House');
insert into district(state, name, chamber) values('Idaho','HR-ID-1','House');
insert into district(state, name, chamber) values('Idaho','HR-ID-2','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-1','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-2','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-3','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-4','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-5','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-6','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-7','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-8','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-9','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-10','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-11','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-12','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-13','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-14','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-15','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-16','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-17','House');
insert into district(state, name, chamber) values('Illinois','HR-IL-18','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-1','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-2','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-3','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-4','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-5','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-6','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-7','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-8','House');
insert into district(state, name, chamber) values('Indiana','HR-IN-9','House');
insert into district(state, name, chamber) values('Iowa','HR-IA-1','House');
insert into district(state, name, chamber) values('Iowa','HR-IA-2','House');
insert into district(state, name, chamber) values('Iowa','HR-IA-3','House');
insert into district(state, name, chamber) values('Iowa','HR-IA-4','House');
insert into district(state, name, chamber) values('Kansas','HR-KS-1','House');
insert into district(state, name, chamber) values('Kansas','HR-KS-2','House');
insert into district(state, name, chamber) values('Kansas','HR-KS-3','House');
insert into district(state, name, chamber) values('Kansas','HR-KS-4','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-1','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-2','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-3','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-4','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-5','House');
insert into district(state, name, chamber) values('Kentucky','HR-KY-6','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-1','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-2','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-3','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-4','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-5','House');
insert into district(state, name, chamber) values('Louisiana','HR-LA-6','House');
insert into district(state, name, chamber) values('Maine','HR-ME-1','House');
insert into district(state, name, chamber) values('Maine','HR-ME-2','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-1','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-2','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-3','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-4','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-5','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-6','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-7','House');
insert into district(state, name, chamber) values('Maryland','HR-MD-8','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-1','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-2','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-3','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-4','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-5','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-6','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-7','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-8','House');
insert into district(state, name, chamber) values('Massachusetts','HR-MA-9','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-1','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-2','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-3','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-4','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-5','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-6','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-7','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-8','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-9','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-10','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-11','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-12','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-13','House');
insert into district(state, name, chamber) values('Michigan','HR-MI-14','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-1','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-2','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-3','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-4','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-5','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-6','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-7','House');
insert into district(state, name, chamber) values('Minnesota','HR-MN-8','House');
insert into district(state, name, chamber) values('Mississippi','HR-MS-1','House');
insert into district(state, name, chamber) values('Mississippi','HR-MS-2','House');
insert into district(state, name, chamber) values('Mississippi','HR-MS-3','House');
insert into district(state, name, chamber) values('Mississippi','HR-MS-4','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-1','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-2','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-3','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-4','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-5','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-6','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-7','House');
insert into district(state, name, chamber) values('Missouri','HR-MO-8','House');
insert into district(state, name, chamber) values('Montana','HR-MT-AL','House');
insert into district(state, name, chamber) values('Nebraska','HR-NE-1','House');
insert into district(state, name, chamber) values('Nebraska','HR-NE-2','House');
insert into district(state, name, chamber) values('Nebraska','HR-NE-3','House');
insert into district(state, name, chamber) values('Nevada','HR-NV-1','House');
insert into district(state, name, chamber) values('Nevada','HR-NV-2','House');
insert into district(state, name, chamber) values('Nevada','HR-NV-3','House');
insert into district(state, name, chamber) values('Nevada','HR-NV-4','House');
insert into district(state, name, chamber) values('New Hampshire','HR-NH-1','House');
insert into district(state, name, chamber) values('New Hampshire','HR-NH-2','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-1','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-2','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-3','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-4','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-5','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-6','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-7','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-8','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-9','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-10','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-11','House');
insert into district(state, name, chamber) values('New Jersey','HR-NJ-12','House');
insert into district(state, name, chamber) values('New Mexico','HR-NM-1','House');
insert into district(state, name, chamber) values('New Mexico','HR-NM-2','House');
insert into district(state, name, chamber) values('New Mexico','HR-NM-3','House');
insert into district(state, name, chamber) values('New York','HR-NY-1','House');
insert into district(state, name, chamber) values('New York','HR-NY-2','House');
insert into district(state, name, chamber) values('New York','HR-NY-3','House');
insert into district(state, name, chamber) values('New York','HR-NY-4','House');
insert into district(state, name, chamber) values('New York','HR-NY-5','House');
insert into district(state, name, chamber) values('New York','HR-NY-6','House');
insert into district(state, name, chamber) values('New York','HR-NY-7','House');
insert into district(state, name, chamber) values('New York','HR-NY-8','House');
insert into district(state, name, chamber) values('New York','HR-NY-9','House');
insert into district(state, name, chamber) values('New York','HR-NY-10','House');
insert into district(state, name, chamber) values('New York','HR-NY-11','House');
insert into district(state, name, chamber) values('New York','HR-NY-12','House');
insert into district(state, name, chamber) values('New York','HR-NY-13','House');
insert into district(state, name, chamber) values('New York','HR-NY-14','House');
insert into district(state, name, chamber) values('New York','HR-NY-15','House');
insert into district(state, name, chamber) values('New York','HR-NY-16','House');
insert into district(state, name, chamber) values('New York','HR-NY-17','House');
insert into district(state, name, chamber) values('New York','HR-NY-18','House');
insert into district(state, name, chamber) values('New York','HR-NY-19','House');
insert into district(state, name, chamber) values('New York','HR-NY-20','House');
insert into district(state, name, chamber) values('New York','HR-NY-21','House');
insert into district(state, name, chamber) values('New York','HR-NY-22','House');
insert into district(state, name, chamber) values('New York','HR-NY-23','House');
insert into district(state, name, chamber) values('New York','HR-NY-24','House');
insert into district(state, name, chamber) values('New York','HR-NY-25','House');
insert into district(state, name, chamber) values('New York','HR-NY-26','House');
insert into district(state, name, chamber) values('New York','HR-NY-27','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-1','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-2','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-3','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-4','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-5','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-6','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-7','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-8','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-9','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-10','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-11','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-12','House');
insert into district(state, name, chamber) values('North Carolina','HR-NC-13','House');
insert into district(state, name, chamber) values('North Dakota','HR-ND-AL','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-1','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-2','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-3','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-4','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-5','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-6','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-7','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-8','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-9','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-10','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-11','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-12','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-13','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-14','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-15','House');
insert into district(state, name, chamber) values('Ohio','HR-OH-16','House');
insert into district(state, name, chamber) values('Oklahoma','HR-OK-1','House');
insert into district(state, name, chamber) values('Oklahoma','HR-OK-2','House');
insert into district(state, name, chamber) values('Oklahoma','HR-OK-3','House');
insert into district(state, name, chamber) values('Oklahoma','HR-OK-4','House');
insert into district(state, name, chamber) values('Oklahoma','HR-OK-5','House');
insert into district(state, name, chamber) values('Oregon','HR-OR-1','House');
insert into district(state, name, chamber) values('Oregon','HR-OR-2','House');
insert into district(state, name, chamber) values('Oregon','HR-OR-3','House');
insert into district(state, name, chamber) values('Oregon','HR-OR-4','House');
insert into district(state, name, chamber) values('Oregon','HR-OR-5','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-1','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-2','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-3','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-4','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-5','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-6','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-7','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-8','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-9','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-10','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-11','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-12','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-13','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-14','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-15','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-16','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-17','House');
insert into district(state, name, chamber) values('Pennsylvania','HR-PA-18','House');
insert into district(state, name, chamber) values('Rhode Island','HR-RI-1','House');
insert into district(state, name, chamber) values('Rhode Island','HR-RI-2','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-1','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-2','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-3','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-4','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-5','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-6','House');
insert into district(state, name, chamber) values('South Carolina','HR-SC-7','House');
insert into district(state, name, chamber) values('South Dakota','HR-SD-AL','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-1','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-2','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-3','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-4','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-5','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-6','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-7','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-8','House');
insert into district(state, name, chamber) values('Tennessee','HR-TN-9','House');
insert into district(state, name, chamber) values('Texas','HR-TX-1','House');
insert into district(state, name, chamber) values('Texas','HR-TX-2','House');
insert into district(state, name, chamber) values('Texas','HR-TX-3','House');
insert into district(state, name, chamber) values('Texas','HR-TX-4','House');
insert into district(state, name, chamber) values('Texas','HR-TX-5','House');
insert into district(state, name, chamber) values('Texas','HR-TX-6','House');
insert into district(state, name, chamber) values('Texas','HR-TX-7','House');
insert into district(state, name, chamber) values('Texas','HR-TX-8','House');
insert into district(state, name, chamber) values('Texas','HR-TX-9','House');
insert into district(state, name, chamber) values('Texas','HR-TX-10','House');
insert into district(state, name, chamber) values('Texas','HR-TX-11','House');
insert into district(state, name, chamber) values('Texas','HR-TX-12','House');
insert into district(state, name, chamber) values('Texas','HR-TX-13','House');
insert into district(state, name, chamber) values('Texas','HR-TX-14','House');
insert into district(state, name, chamber) values('Texas','HR-TX-15','House');
insert into district(state, name, chamber) values('Texas','HR-TX-16','House');
insert into district(state, name, chamber) values('Texas','HR-TX-17','House');
insert into district(state, name, chamber) values('Texas','HR-TX-18','House');
insert into district(state, name, chamber) values('Texas','HR-TX-19','House');
insert into district(state, name, chamber) values('Texas','HR-TX-20','House');
insert into district(state, name, chamber) values('Texas','HR-TX-21','House');
insert into district(state, name, chamber) values('Texas','HR-TX-22','House');
insert into district(state, name, chamber) values('Texas','HR-TX-23','House');
insert into district(state, name, chamber) values('Texas','HR-TX-24','House');
insert into district(state, name, chamber) values('Texas','HR-TX-25','House');
insert into district(state, name, chamber) values('Texas','HR-TX-26','House');
insert into district(state, name, chamber) values('Texas','HR-TX-27','House');
insert into district(state, name, chamber) values('Texas','HR-TX-28','House');
insert into district(state, name, chamber) values('Texas','HR-TX-29','House');
insert into district(state, name, chamber) values('Texas','HR-TX-30','House');
insert into district(state, name, chamber) values('Texas','HR-TX-31','House');
insert into district(state, name, chamber) values('Texas','HR-TX-32','House');
insert into district(state, name, chamber) values('Texas','HR-TX-33','House');
insert into district(state, name, chamber) values('Texas','HR-TX-34','House');
insert into district(state, name, chamber) values('Texas','HR-TX-35','House');
insert into district(state, name, chamber) values('Texas','HR-TX-36','House');
insert into district(state, name, chamber) values('Utah','HR-UT-1','House');
insert into district(state, name, chamber) values('Utah','HR-UT-2','House');
insert into district(state, name, chamber) values('Utah','HR-UT-3','House');
insert into district(state, name, chamber) values('Utah','HR-UT-4','House');
insert into district(state, name, chamber) values('Vermont','HR-VT-AL','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-1','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-2','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-3','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-4','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-5','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-6','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-7','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-8','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-9','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-10','House');
insert into district(state, name, chamber) values('Virginia','HR-VA-11','House');
insert into district(state, name, chamber) values('Washington','HR-WA-1','House');
insert into district(state, name, chamber) values('Washington','HR-WA-2','House');
insert into district(state, name, chamber) values('Washington','HR-WA-3','House');
insert into district(state, name, chamber) values('Washington','HR-WA-4','House');
insert into district(state, name, chamber) values('Washington','HR-WA-5','House');
insert into district(state, name, chamber) values('Washington','HR-WA-6','House');
insert into district(state, name, chamber) values('Washington','HR-WA-7','House');
insert into district(state, name, chamber) values('Washington','HR-WA-8','House');
insert into district(state, name, chamber) values('Washington','HR-WA-9','House');
insert into district(state, name, chamber) values('Washington','HR-WA-10','House');
insert into district(state, name, chamber) values('West Virginia','HR-WV-1','House');
insert into district(state, name, chamber) values('West Virginia','HR-WV-2','House');
insert into district(state, name, chamber) values('West Virginia','HR-WV-3','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-1','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-2','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-3','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-4','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-5','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-6','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-7','House');
insert into district(state, name, chamber) values('Wisconsin','HR-WI-8','House');
insert into district(state, name, chamber) values('Wyoming','HR-WY-AL','House');
