insert into state (name) values ('Alabama');
insert into state (name) values ('Alaska');
insert into state (name) values ('Arizona');
insert into state (name) values ('Arkansas');
insert into state (name) values ('California');
insert into state (name) values ('Colorado');
insert into state (name) values ('Connecticut');
insert into state (name) values ('Delaware');
insert into state (name) values ('Florida');
insert into state (name) values ('Georgia');
insert into state (name) values ('Hawaii');
insert into state (name) values ('Idaho');
insert into state (name) values ('Illinois');
insert into state (name) values ('Indiana');
insert into state (name) values ('Iowa');
insert into state (name) values ('Kansas');
insert into state (name) values ('Kentucky');
insert into state (name) values ('Louisiana');
insert into state (name) values ('Maine');
insert into state (name) values ('Maryland');
insert into state (name) values ('Massachusetts');
insert into state (name) values ('Michigan');
insert into state (name) values ('Minnesota');
insert into state (name) values ('Mississippi');
insert into state (name) values ('Missouri');
insert into state (name) values ('Montana');
insert into state (name) values ('Nebraska');
insert into state (name) values ('Nevada');
insert into state (name) values ('New Hampshire');
insert into state (name) values ('New Jersey');
insert into state (name) values ('New Mexico');
insert into state (name) values ('New York');
insert into state (name) values ('North Carolina');
insert into state (name) values ('North Dakota');
insert into state (name) values ('Ohio');
insert into state (name) values ('Oklahoma');
insert into state (name) values ('Oregon');
insert into state (name) values ('Pennsylvania');
insert into state (name) values ('Rhode Island');
insert into state (name) values ('South Carolina');
insert into state (name) values ('South Dakota');
insert into state (name) values ('Tennessee');
insert into state (name) values ('Texas');
insert into state (name) values ('Utah');
insert into state (name) values ('Vermont');
insert into state (name) values ('Virginia');
insert into state (name) values ('Washington');
insert into state (name) values ('West Virginia');
insert into state (name) values ('Wisconsin');
insert into state (name) values ('Wyoming');
