insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-1', 115, 'Byrne', 'Bradley', 'republican', 1955, 'Duke University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-2', 115, 'Roby', 'Martha', 'republican', 1976, 'New York University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-3', 115, 'Rogers', 'Mike', 'republican', 1958, 'Jacksonville State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-4', 115, 'Aderholt', 'Robert', 'republican', 1965, 'University of North Alabama');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-5', 115, 'Brooks', 'Mo', 'republican', 1954, 'Duke University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-6', 115, 'Palmer', 'Gary', 'republican', 1954, 'University of Alabama');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AL-7', 115, 'Sewell', 'Terri', 'democrat', 1965, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AK-AL', 115, 'Young', 'Don', 'republican', 1933, 'Yuba College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-1', 115, 'OHalleran', 'Tom', 'democrat', 1946, 'Lewis University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-2', 115, 'Kirkpatrick', 'Ann', 'democrat', 1950, 'University of Arizona');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-3', 115, 'Grijalva', 'Raúl', 'democrat', 1948, 'University of Arizona');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-4', 115, 'Gosar', 'Paul', 'republican', 1958, 'Creighton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-5', 115, 'Biggs', 'Andy', 'republican', 1958, 'Brigham Young University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-6', 115, 'Schweikert', 'David', 'republican', 1962, 'Arizona State University Tempe campus');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-7', 115, 'Gallego', 'Ruben', 'democrat', 1979, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-8', 115, 'Lesko', 'Debbie', 'republican', 1958, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AZ-9', 115, 'Stanton', 'Greg', 'democrat', 1970, 'Marquette University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AR-1', 115, 'Crawford', 'Rick', 'republican', 1966, 'Arkansas State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AR-2', 115, 'Hill', 'French', 'republican', 1956, 'Vanderbilt University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AR-3', 115, 'Womack', 'Steve', 'republican', 1957, 'Arkansas Tech University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-AR-4', 115, 'Westerman', 'Bruce', 'republican', 1967, 'University of Arkansas');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-1', 115, 'LaMalfa', 'Doug', 'republican', 1960, 'Butte College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-2', 115, 'Huffman', 'Jared', 'democrat', 1964, 'University of California, Santa Barbara');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-3', 115, 'Garamendi', 'John', 'democrat', 1945, 'University of California, Berkeley');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-4', 115, 'McClintock', 'Tom', 'republican', 1956, 'University of California, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-5', 115, 'Thompson', 'Mike', 'democrat', 1951, 'Napa Valley College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-6', 115, 'Matsui', 'Doris', 'democrat', 1944, 'University of California, Berkeley');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-7', 115, 'Bera', 'Ami', 'democrat', 1965, 'University of California, Irvine');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-8', 115, 'Cook', 'Paul', 'republican', 1943, 'Southern Connecticut State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-9', 115, 'McNerney', 'Jerry', 'democrat', 1951, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-10', 115, 'Harder', 'Josh', 'democrat', 1986, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-11', 115, 'DeSaulnier', 'Mark', 'democrat', 1952, 'College of the Holy Cross');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-12', 115, 'Pelosi', 'Nancy', 'democrat', 1940, 'Trinity Washington University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-13', 115, 'Lee', 'Barbara', 'democrat', 1946, 'Mills College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-14', 115, 'Speier', 'Jackie', 'democrat', 1950, 'University of California, Davis');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-15', 115, 'Swalwell', 'Eric', 'democrat', 1980, 'Campbell University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-16', 115, 'Costa', 'Jim', 'democrat', 1952, 'California State University, Fresno');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-17', 115, 'Khanna', 'Ro', 'democrat', 1976, 'University of Chicago');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-18', 115, 'Eshoo', 'Anna', 'democrat', 1942, 'Cañada College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-19', 115, 'Lofgren', 'Zoe', 'democrat', 1947, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-20', 115, 'Panetta', 'Jimmy', 'democrat', 1969, 'Monterey Peninsula College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-21', 115, 'Cox', 'TJ', 'democrat', 1963, 'University of Nevada, Reno');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-22', 115, 'Nunes', 'Devin', 'republican', 1973, 'College of the Sequoias');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-23', 115, 'McCarthy', 'Kevin', 'republican', 1965, 'California State University, Bakersfield');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-24', 115, 'Carbajal', 'Salud', 'democrat', 1964, 'University of California, Santa Barbara');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-26', 115, 'Brownley', 'Julia', 'democrat', 1952, 'George Washington University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-27', 115, 'Chu', 'Judy', 'democrat', 1953, 'University of California, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-28', 115, 'Schiff', 'Adam', 'democrat', 1960, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-29', 115, 'Cárdenas', 'Tony', 'democrat', 1963, 'University of California, Santa Barbara');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-30', 115, 'Sherman', 'Brad', 'democrat', 1954, 'University of California, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-31', 115, 'Aguilar', 'Pete', 'democrat', 1979, 'University of Redlands');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-32', 115, 'Napolitano', 'Grace', 'democrat', 1936, 'Cerritos College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-33', 115, 'Lieu', 'Ted', 'democrat', 1969, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-35', 115, 'Torres', 'Norma', 'democrat', 1965, 'National Labor College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-36', 115, 'Ruiz', 'Raul', 'democrat', 1972, 'University of California, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-37', 115, 'Bass', 'Karen', 'democrat', 1953, 'San Diego State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-38', 115, 'Sánchez', 'Linda', 'democrat', 1969, 'University of California, Berkeley');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-39', 115, 'Cisneros', 'Gil', 'democrat', 1971, 'George Washington University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-40', 115, 'Roybal-Allard', 'Lucille', 'democrat', 1941, 'California State University, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-41', 115, 'Takano', 'Mark', 'democrat', 1960, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-42', 115, 'Calvert', 'Ken', 'republican', 1953, 'Chaffey College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-43', 115, 'Waters', 'Maxine', 'democrat', 1938, 'California State University, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-44', 115, 'Barragán', 'Nanette', 'democrat', 1976, 'University of California, Los Angeles');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-45', 115, 'Porter', 'Katie', 'democrat', 1974, 'Yale University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-46', 115, 'Correa', 'Lou', 'democrat', 1958, 'California State University, Fullerton');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-47', 115, 'Lowenthal', 'Alan', 'democrat', 1941, 'Hobart and William Smith Colleges');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-48', 115, 'Rouda', 'Harley', 'democrat', 1961, 'University of Kentucky');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-49', 115, 'Levin', 'Mike', 'democrat', 1978, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-50', 115, 'Hunter', 'Duncan D.', 'republican', 1976, 'San Diego State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CA-52', 115, 'Peters', 'Scott', 'democrat', 1958, 'Duke University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-1', 115, 'DeGette', 'Diana', 'democrat', 1957, 'Colorado College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-2', 115, 'Neguse', 'Joe', 'democrat', 1984, 'University of Colorado, Boulder');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-3', 115, 'Tipton', 'Scott', 'republican', 1956, 'Fort Lewis College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-4', 115, 'Buck', 'Ken', 'republican', 1959, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-5', 115, 'Lamborn', 'Doug', 'republican', 1954, 'University of Kansas');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-6', 115, 'Crow', 'Jason', 'democrat', 1979, 'University of Wisconsin, Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CO-7', 115, 'Perlmutter', 'Ed', 'democrat', 1953, 'University of Colorado Boulder');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CT-1', 115, 'Larson', 'John B.', 'democrat', 1948, 'Central Connecticut State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CT-2', 115, 'Courtney', 'Joe', 'democrat', 1953, 'Tufts University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CT-3', 115, 'DeLauro', 'Rosa', 'democrat', 1943, 'Marymount College, Tarrytown');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CT-4', 115, 'Himes', 'Jim', 'democrat', 1966, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-CT-5', 115, 'Hayes', 'Jahana', 'democrat', 1973, 'Naugatuck Valley Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-DE-AL', 115, 'Blunt', 'Rochester Lisa', 'democrat', 1962, 'Fairleigh Dickinson University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-1', 115, 'Gaetz', 'Matt', 'republican', 1982, 'Florida State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-2', 115, 'Dunn', 'Neal', 'republican', 1953, 'Washington and Lee University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-3', 115, 'Yoho', 'Ted', 'republican', 1955, 'Broward College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-4', 115, 'Rutherford', 'John', 'republican', 1952, 'Florida State College at Jacksonville');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-5', 115, 'Lawson', 'Al', 'democrat', 1948, 'Florida A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-6', 115, 'Waltz', 'Michael', 'republican', 1974, 'Virginia Military Institute');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-7', 115, 'Murphy', 'Stephanie', 'democrat', 1978, 'College of William & Mary');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-8', 115, 'Posey', 'Bill', 'republican', 1947, 'Eastern Florida State College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-9', 115, 'Soto', 'Darren', 'democrat', 1978, 'Rutgers University–New Brunswick');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-10', 115, 'Demings', 'Val', 'democrat', 1957, 'Florida State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-11', 115, 'Webster', 'Daniel', 'republican', 1949, 'Georgia Institute of Technology');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-12', 115, 'Bilirakis', 'Gus', 'republican', 1963, 'St. Petersburg College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-13', 115, 'Crist', 'Charlie', 'democrat', 1956, 'Wake Forest University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-14', 115, 'Castor', 'Kathy', 'democrat', 1966, 'Emory University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-15', 115, 'Spano', 'Ross', 'republican', 1966, 'University of South Florida');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-16', 115, 'Buchanan', 'Vern', 'republican', 1951, 'Cleary University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-17', 115, 'Steube', 'Greg', 'republican', 1978, 'University of Florida');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-18', 115, 'Mast', 'Brian', 'republican', 1980, 'Palm Beach Atlantic University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-19', 115, 'Rooney', 'Francis', 'republican', 1953, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-20', 115, 'Hastings', 'Alcee', 'democrat', 1936, 'Howard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-21', 115, 'Frankel', 'Lois', 'democrat', 1948, 'Boston University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-22', 115, 'Deutch', 'Ted', 'democrat', 1966, 'University of Michigan');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-23', 115, 'Wasserman', 'Schultz Debbie', 'democrat', 1966, 'University of Florida');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-FL-24', 115, 'Wilson', 'Frederica', 'democrat', 1942, 'Fisk University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-1', 115, 'Carter', 'Buddy', 'republican', 1957, 'Young Harris College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-2', 115, 'Bishop', 'Sanford', 'democrat', 1947, 'Morehouse College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-3', 115, 'Ferguson', 'Drew', 'republican', 1966, 'University of Georgia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-4', 115, 'Johnson', 'Hank', 'democrat', 1954, 'Clark Atlanta University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-5', 115, 'Lewis', 'John', 'democrat', 1940, 'American Baptist College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-6', 115, 'McBath', 'Lucy', 'democrat', 1960, 'Virginia State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-7', 115, 'Woodall', 'Rob', 'republican', 1970, 'Furman University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-8', 115, 'Scott', 'Austin', 'republican', 1969, 'University of Georgia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-9', 115, 'Collins', 'Doug', 'republican', 1966, 'University of North Georgia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-10', 115, 'Hice', 'Jody', 'republican', 1960, 'Asbury University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-11', 115, 'Loudermilk', 'Barry', 'republican', 1963, 'Air University (United States Air Force)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-12', 115, 'Allen', 'Rick W.', 'republican', 1951, 'Auburn University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-13', 115, 'Scott', 'David', 'democrat', 1945, 'Florida A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-GA-14', 115, 'Graves', 'Tom', 'republican', 1970, 'University of Georgia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-HI-1', 115, 'Case', 'Ed', 'democrat', 1952, 'Williams College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-ID-1', 115, 'Fulcher', 'Russ', 'republican', 1962, 'Boise State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-ID-2', 115, 'Simpson', 'Mike', 'republican', 1950, 'Utah State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-1', 115, 'Rush', 'Bobby', 'democrat', 1946, 'Roosevelt University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-2', 115, 'Kelly', 'Robin', 'democrat', 1956, 'Bradley University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-3', 115, 'Lipinski', 'Dan', 'democrat', 1966, 'Northwestern University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-5', 115, 'Quigley', 'Mike', 'democrat', 1958, 'Roosevelt University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-6', 115, 'Casten', 'Sean', 'democrat', 1971, 'Middlebury College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-7', 115, 'Davis', 'Danny K.', 'democrat', 1941, 'University of Arkansas at Pine Bluff');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-8', 115, 'Krishnamoorthi', 'Raja', 'democrat', 1973, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-9', 115, 'Schakowsky', 'Jan', 'democrat', 1944, 'University of Illinois at Urbana–Champaign');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-10', 115, 'Schneider', 'Brad', 'democrat', 1961, 'Northwestern University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-11', 115, 'Foster', 'Bill', 'democrat', 1955, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born) values('HR-IL-12', 115, 'Bost', 'Mike', 'republican', 1960);
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-13', 115, 'Davis', 'Rodney', 'republican', 1970, 'Millikin University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-14', 115, 'Underwood', 'Lauren', 'democrat', 1986, 'University of Michigan');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-15', 115, 'Shimkus', 'John', 'republican', 1958, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-16', 115, 'Kinzinger', 'Adam', 'republican', 1978, 'Illinois State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-17', 115, 'Bustos', 'Cheri', 'democrat', 1961, 'University of Maryland, College Park');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IL-18', 115, 'LaHood', 'Darin', 'republican', 1968, 'Loras College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-1', 115, 'Visclosky', 'Pete', 'democrat', 1949, 'Indiana University Northwest');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-2', 115, 'Walorski', 'Jackie', 'republican', 1963, 'Liberty University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-3', 115, 'Banks', 'Jim', 'republican', 1979, 'Indiana University Bloomington');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-4', 115, 'Baird', 'Jim', 'republican', 1945, 'Purdue University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-5', 115, 'Brooks', 'Susan', 'republican', 1960, 'Miami University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-6', 115, 'Pence', 'Greg', 'republican', 1956, 'Loyola University Chicago');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-7', 115, 'Carson', 'André', 'democrat', 1974, 'Concordia University Wisconsin');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-8', 115, 'Bucshon', 'Larry', 'republican', 1962, 'University of Illinois at Urbana–Champaign');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IN-9', 115, 'Hollingsworth', 'Trey', 'republican', 1983, 'University of Pennsylvania');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IA-1', 115, 'Finkenauer', 'Abby', 'democrat', 1988, 'Drake University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IA-2', 115, 'Loebsack', 'Dave', 'democrat', 1952, 'Iowa State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IA-3', 115, 'Axne', 'Cindy', 'democrat', 1965, 'University of Iowa');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-IA-4', 115, 'King', 'Steve', 'republican', 1949, 'Northwest Missouri State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KS-1', 115, 'Marshall', 'Roger', 'republican', 1960, 'Kansas State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KS-2', 115, 'Watkins', 'Steve', 'republican', 1976, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KS-3', 115, 'Davids', 'Sharice', 'democrat', 1980, 'Haskell Indian Nations University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KS-4', 115, 'Estes', 'Ron', 'republican', 1956, 'Tennessee Technological University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-1', 115, 'Comer', 'James', 'republican', 1972, 'Western Kentucky University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-2', 115, 'Guthrie', 'Brett', 'republican', 1964, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-3', 115, 'Yarmuth', 'John', 'democrat', 1947, 'Yale University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-4', 115, 'Massie', 'Thomas', 'republican', 1971, 'Massachusetts Institute of Technology');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-5', 115, 'Rogers', 'Hal', 'republican', 1937, 'Western Kentucky University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-KY-6', 115, 'Barr', 'Andy', 'republican', 1973, 'University of Virginia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-1', 115, 'Scalise', 'Steve', 'republican', 1965, 'Louisiana State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-2', 115, 'Richmond', 'Cedric', 'democrat', 1973, 'Morehouse College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-3', 115, 'Higgins', 'Clay', 'republican', 1961, 'Louisiana State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-4', 115, 'Johnson', 'Mike', 'republican', 1972, 'Louisiana State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-5', 115, 'Abraham', 'Ralph', 'republican', 1954, 'Louisiana State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-LA-6', 115, 'Graves', 'Garret', 'republican', 1972, 'University of Alabama');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-ME-1', 115, 'Pingree', 'Chellie', 'democrat', 1955, 'University of Southern Maine');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-ME-2', 115, 'Golden', 'Jared', 'democrat', 1982, 'University of Maine at Farmington');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-1', 115, 'Harris', 'Andy', 'republican', 1957, 'Johns Hopkins University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-2', 115, 'Ruppersberger', 'Dutch', 'democrat', 1946, 'Baltimore City College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-3', 115, 'Sarbanes', 'John', 'democrat', 1962, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-4', 115, 'Brown', 'Anthony G.', 'democrat', 1961, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-5', 115, 'Hoyer', 'Steny', 'democrat', 1939, 'University of Maryland, College Park');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-6', 115, 'Trone', 'David', 'democrat', 1955, 'Furman University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MD-8', 115, 'Raskin', 'Jamie', 'democrat', 1962, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-1', 115, 'Neal', 'Richard', 'democrat', 1949, 'Holyoke Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-2', 115, 'McGovern', 'Jim', 'democrat', 1959, 'American University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-3', 115, 'Trahan', 'Lori', 'democrat', 1973, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-4', 115, 'Kennedy', 'Joe', 'democrat', 1980, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-5', 115, 'Clark', 'Katherine', 'democrat', 1963, 'St. Lawrence University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-6', 115, 'Moulton', 'Seth', 'democrat', 1978, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-7', 115, 'Pressley', 'Ayanna', 'democrat', 1974, 'Boston University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-8', 115, 'Lynch', 'Stephen F.', 'democrat', 1955, 'Wentworth Institute of Technology');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MA-9', 115, 'Keating', 'Bill', 'democrat', 1952, 'Boston College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-1', 115, 'Bergman', 'Jack', 'republican', 1947, 'Gustavus Adolphus College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-2', 115, 'Huizenga', 'Bill', 'republican', 1969, 'Calvin College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-3', 115, 'Amash', 'Justin', 'independent', 1980, 'University of Michigan');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-4', 115, 'Moolenaar', 'John', 'republican', 1961, 'Hope College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-5', 115, 'Kildee', 'Dan', 'democrat', 1958, 'University of Michigan–Flint');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-6', 115, 'Upton', 'Fred', 'republican', 1953, 'University of Michigan');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-7', 115, 'Walberg', 'Tim', 'republican', 1951, 'Western Illinois University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-8', 115, 'Slotkin', 'Elissa', 'democrat', 1976, 'Cornell University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-9', 115, 'Levin', 'Andy', 'democrat', 1960, 'Williams College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-10', 115, 'Mitchell', 'Paul', 'republican', 1961, 'Michigan State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-11', 115, 'Stevens', 'Haley', 'democrat', 1983, 'American University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-12', 115, 'Dingell', 'Debbie', 'democrat', 1953, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-13', 115, 'Tlaib', 'Rashida', 'democrat', 1976, 'Wayne State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MI-14', 115, 'Lawrence', 'Brenda', 'democrat', 1954, 'University of Detroit Mercy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-1', 115, 'Hagedorn', 'Jim', 'republican', 1962, 'George Mason University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-2', 115, 'Craig', 'Angie', 'democrat', 1972, 'University of Memphis');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-3', 115, 'Phillips', 'Dean', 'democrat', 1969, 'Brown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-4', 115, 'McCollum', 'Betty', 'democrat', 1954, 'St. Catherine University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-5', 115, 'Omar', 'Ilhan', 'democrat', 1981, 'North Dakota State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-6', 115, 'Emmer', 'Tom', 'republican', 1961, 'Boston College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-7', 115, 'Peterson', 'Collin', 'democrat', 1944, 'Minnesota State University Moorhead');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MN-8', 115, 'Stauber', 'Pete', 'republican', 1966, 'Lake Superior State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MS-1', 115, 'Kelly', 'Trent', 'republican', 1966, 'East Central Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MS-2', 115, 'Thompson', 'Bennie', 'democrat', 1948, 'Tougaloo College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MS-3', 115, 'Guest', 'Michael', 'republican', 1970, 'Mississippi State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MS-4', 115, 'Palazzo', 'Steven', 'republican', 1970, 'University of Southern Mississippi');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-1', 115, 'Clay', 'Lacy', 'democrat', 1956, 'University of Maryland, College Park');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-2', 115, 'Wagner', 'Ann', 'republican', 1962, 'University of Missouri');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-3', 115, 'Luetkemeyer', 'Blaine', 'republican', 1952, 'Lincoln University (Missouri)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-4', 115, 'Hartzler', 'Vicky', 'republican', 1960, 'University of Missouri');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-5', 115, 'Cleaver', 'Emanuel', 'democrat', 1944, 'Prairie View A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-6', 115, 'Graves', 'Sam', 'republican', 1963, 'University of Missouri');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-7', 115, 'Long', 'Billy', 'republican', 1955, 'University of Missouri');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MO-8', 115, 'Smith', 'Jason', 'republican', 1980, 'University of Missouri');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-MT-AL', 115, 'Gianforte', 'Greg', 'republican', 1961, 'Stevens Institute of Technology');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NE-1', 115, 'Fortenberry', 'Jeff', 'republican', 1960, 'Louisiana State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NE-2', 115, 'Bacon', 'Don', 'republican', 1963, 'Northern Illinois University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NE-3', 115, 'Smith', 'Adrian', 'republican', 1970, 'Liberty University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NV-1', 115, 'Titus', 'Dina', 'democrat', 1950, 'College of William & Mary');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NV-2', 115, 'Amodei', 'Mark', 'republican', 1958, 'University of Nevada, Reno');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NV-3', 115, 'Lee', 'Susie', 'democrat', 1966, 'Carnegie Mellon University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NV-4', 115, 'Horsford', 'Steven', 'democrat', 1973, 'University of Nevada, Reno');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NH-1', 115, 'Pappas', 'Chris', 'democrat', 1980, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NH-2', 115, 'Kuster', 'Ann', 'democrat', 1956, 'Dartmouth College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-1', 115, 'Norcross', 'Donald', 'democrat', 1958, 'Camden County College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-2', 115, 'Van', 'Drew Jeff', 'democrat', 1953, 'Rutgers University–New Brunswick');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-3', 115, 'Kim', 'Andy', 'democrat', 1982, 'Deep Springs College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-4', 115, 'Smith', 'Chris', 'republican', 1953, 'The College of New Jersey');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-5', 115, 'Gottheimer', 'Josh', 'democrat', 1975, 'University of Pennsylvania');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-6', 115, 'Pallone', 'Frank', 'democrat', 1951, 'Middlebury College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-7', 115, 'Malinowski', 'Tom', 'democrat', 1965, 'University of California, Berkeley');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-8', 115, 'Sires', 'Albio', 'democrat', 1951, 'Saint Peters University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-9', 115, 'Pascrell', 'Bill', 'democrat', 1937, 'Fordham University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-10', 115, 'Payne', 'Jr. Donald', 'democrat', 1958, 'Kean University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-11', 115, 'Sherrill', 'Mikie', 'democrat', 1972, 'United States Naval Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NJ-12', 115, 'Watson', 'Coleman Bonnie', 'democrat', 1945, 'Rutgers University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NM-1', 115, 'Haaland', 'Deb', 'democrat', 1960, 'University of New Mexico');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NM-2', 115, 'Torres', 'Small Xochitl', 'democrat', 1984, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NM-3', 115, 'Ben', 'Ray', 'democrat', 1972, 'University of New Mexico');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-1', 115, 'Zeldin', 'Lee', 'republican', 1980, 'University at Albany, SUNY');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-2', 115, 'King', 'Peter T.', 'republican', 1944, 'St. Francis College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-3', 115, 'Suozzi', 'Thomas', 'democrat', 1962, 'Boston College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-4', 115, 'Rice', 'Kathleen', 'democrat', 1965, 'Catholic University of America');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-5', 115, 'Meeks', 'Gregory', 'democrat', 1953, 'Adelphi University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-6', 115, 'Meng', 'Grace', 'democrat', 1975, 'University of Michigan');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-7', 115, 'Velázquez', 'Nydia', 'democrat', 1953, 'University of Puerto Rico, Río Piedras Campus');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-8', 115, 'Jeffries', 'Hakeem', 'democrat', 1970, 'Binghamton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-9', 115, 'Clarke', 'Yvette', 'democrat', 1964, 'Oberlin College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-10', 115, 'Nadler', 'Jerry', 'democrat', 1947, 'Columbia University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-11', 115, 'Rose', 'Max', 'democrat', 1986, 'Wesleyan University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-12', 115, 'Maloney', 'Carolyn', 'democrat', 1946, 'Greensboro College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-13', 115, 'Espaillat', 'Adriano', 'democrat', 1954, 'Queens College, City University of New York');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-14', 115, 'Ocasio-Cortez', 'Alexandria', 'democrat', 1989, 'Boston University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-15', 115, 'Serrano', 'José E.', 'democrat', 1943, 'Lehman College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-16', 115, 'Engel', 'Eliot', 'democrat', 1947, 'Lehman College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-17', 115, 'Lowey', 'Nita', 'democrat', 1937, 'Mount Holyoke College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-18', 115, 'Maloney', 'Sean Patrick', 'democrat', 1966, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-19', 115, 'Delgado', 'Antonio', 'democrat', 1977, 'Colgate University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-20', 115, 'Tonko', 'Paul', 'democrat', 1949, 'Clarkson University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-21', 115, 'Stefanik', 'Elise', 'republican', 1984, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-22', 115, 'Brindisi', 'Anthony', 'democrat', 1978, 'Mohawk Valley Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-23', 115, 'Reed', 'Tom', 'republican', 1971, 'Alfred University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-24', 115, 'Katko', 'John', 'republican', 1962, 'Niagara University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-25', 115, 'Morelle', 'Joseph', 'democrat', 1957, 'State University of New York at Geneseo');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NY-26', 115, 'Higgins', 'Brian', 'democrat', 1959, 'Buffalo State College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-1', 115, 'Butterfield', 'G. K.', 'democrat', 1947, 'North Carolina Central University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-2', 115, 'Holding', 'George', 'republican', 1968, 'Wake Forest University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-3', 115, 'Murphy', 'Greg', 'republican', 1963, 'Davidson College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-4', 115, 'Price', 'David', 'democrat', 1940, 'Mars Hill University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-5', 115, 'Foxx', 'Virginia', 'republican', 1943, 'University of North Carolina at Chapel Hill');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-6', 115, 'Walker', 'Mark', 'republican', 1969, 'Trinity Baptist College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-7', 115, 'Rouzer', 'David', 'republican', 1972, 'North Carolina State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-8', 115, 'Hudson', 'Richard', 'republican', 1971, 'University of North Carolina at Charlotte');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-9', 115, 'Bishop', 'Dan', 'republican', 1964, 'University of North Carolina at Chapel Hill');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-10', 115, 'McHenry', 'Patrick', 'republican', 1975, 'North Carolina State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-11', 115, 'Meadows', 'Mark', 'republican', 1959, 'Florida State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-12', 115, 'Adams', 'Alma', 'democrat', 1946, 'North Carolina A&T State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-NC-13', 115, 'Budd', 'Ted', 'republican', 1971, 'Appalachian State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-ND-AL', 115, 'Armstrong', 'Kelly', 'republican', 1976, 'University of North Dakota');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-1', 115, 'Chabot', 'Steve', 'republican', 1953, 'College of William & Mary');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-2', 115, 'Wenstrup', 'Brad', 'republican', 1958, 'University of Cincinnati');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-3', 115, 'Beatty', 'Joyce', 'democrat', 1950, 'Central State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-4', 115, 'Jordan', 'Jim', 'republican', 1964, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-5', 115, 'Latta', 'Bob', 'republican', 1956, 'Bowling Green State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-6', 115, 'Johnson', 'Bill', 'republican', 1954, 'Troy University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-7', 115, 'Gibbs', 'Bob', 'republican', 1954, 'Ohio State University Agricultural Technical Institute');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-8', 115, 'Davidson', 'Warren', 'republican', 1970, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-9', 115, 'Kaptur', 'Marcy', 'democrat', 1946, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-10', 115, 'Turner', 'Mike', 'republican', 1960, 'Ohio Northern University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-11', 115, 'Fudge', 'Marcia', 'democrat', 1952, 'Ohio State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-12', 115, 'Balderson', 'Troy', 'republican', 1962, 'Muskingum University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-13', 115, 'Ryan', 'Tim', 'democrat', 1973, 'Youngstown State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-14', 115, 'Joyce', 'David', 'republican', 1957, 'University of Dayton');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-15', 115, 'Stivers', 'Steve', 'republican', 1965, 'Ohio State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OH-16', 115, 'Gonzalez', 'Anthony', 'republican', 1984, 'Ohio State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OK-1', 115, 'Hern', 'Kevin', 'republican', 1961, 'Arkansas Tech University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OK-2', 115, 'Mullin', 'Markwayne', 'republican', 1977, 'Missouri Valley College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OK-3', 115, 'Lucas', 'Frank', 'republican', 1960, 'Oklahoma State University–Stillwater');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OK-4', 115, 'Cole', 'Tom', 'republican', 1949, 'Grinnell College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OK-5', 115, 'Horn', 'Kendra', 'democrat', 1976, 'University of Tulsa');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OR-1', 115, 'Bonamici', 'Suzanne', 'democrat', 1954, 'Lane Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OR-2', 115, 'Walden', 'Greg', 'republican', 1957, 'University of Oregon');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OR-3', 115, 'Blumenauer', 'Earl', 'democrat', 1948, 'Lewis & Clark College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OR-4', 115, 'DeFazio', 'Peter', 'democrat', 1947, 'Tufts University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-OR-5', 115, 'Schrader', 'Kurt', 'democrat', 1951, 'Cornell University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-1', 115, 'Fitzpatrick', 'Brian', 'republican', 1973, 'La Salle University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-2', 115, 'Boyle', 'Brendan', 'democrat', 1977, 'University of Notre Dame');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-3', 115, 'Evans', 'Dwight', 'democrat', 1954, 'Community College of Philadelphia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-4', 115, 'Dean', 'Madeleine', 'democrat', 1959, 'La Salle University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-5', 115, 'Scanlon', 'Mary Gay', 'democrat', 1959, 'Colgate University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-6', 115, 'Houlahan', 'Chrissy', 'democrat', 1967, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-7', 115, 'Wild', 'Susan', 'democrat', 1957, 'American University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-8', 115, 'Cartwright', 'Matt', 'democrat', 1961, 'Hamilton College (New York)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-9', 115, 'Meuser', 'Dan', 'republican', 1964, 'State University of New York Maritime College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-10', 115, 'Perry', 'Scott', 'republican', 1962, 'Pennsylvania State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-11', 115, 'Smucker', 'Lloyd', 'republican', 1964, 'Lebanon Valley College');
insert into representative(district, congress_number, last, first, party, year_born) values('HR-PA-12', 115, 'Keller', 'Fred', 'republican', 1965);
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-13', 115, 'Joyce', 'John', 'republican', 1957, 'Penn State Altoona');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-14', 115, 'Reschenthaler', 'Guy', 'republican', 1983, 'Penn State Erie, The Behrend College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-15', 115, 'Thompson', 'Glenn', 'republican', 1959, 'Pennsylvania State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-16', 115, 'Kelly', 'Mike', 'republican', 1948, 'University of Notre Dame');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-17', 115, 'Lamb', 'Conor', 'democrat', 1984, 'University of Pennsylvania');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-PA-18', 115, 'Doyle', 'Mike', 'democrat', 1953, 'Pennsylvania State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-RI-1', 115, 'Cicilline', 'David', 'democrat', 1961, 'Brown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-RI-2', 115, 'Langevin', 'James', 'democrat', 1964, 'Rhode Island College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-1', 115, 'Cunningham', 'Joe', 'democrat', 1982, 'College of Charleston');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-3', 115, 'Duncan', 'Jeff', 'republican', 1966, 'Clemson University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-4', 115, 'Timmons', 'William', 'republican', 1984, 'George Washington University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-5', 115, 'Norman', 'Ralph', 'republican', 1953, 'Presbyterian College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-6', 115, 'Clyburn', 'Jim', 'democrat', 1940, 'South Carolina State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SC-7', 115, 'Rice', 'Tom', 'republican', 1957, 'University of South Carolina');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-SD-AL', 115, 'Johnson', 'Dusty', 'republican', 1976, 'University of South Dakota');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-1', 115, 'Roe', 'Phil', 'republican', 1945, 'Austin Peay State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-2', 115, 'Burchett', 'Tim', 'republican', 1964, 'University of Tennessee');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-3', 115, 'Fleischmann', 'Chuck', 'republican', 1962, 'University of Illinois at Urbana–Champaign');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-4', 115, 'DesJarlais', 'Scott', 'republican', 1964, 'University of South Dakota');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-5', 115, 'Cooper', 'Jim', 'democrat', 1954, 'University of North Carolina at Chapel Hill');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-6', 115, 'Rose', 'John', 'republican', 1965, 'Tennessee Technological University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-7', 115, 'Green', 'Mark E.', 'republican', 1964, 'United States Military Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-8', 115, 'Kustoff', 'David', 'republican', 1966, 'University of Memphis');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TN-9', 115, 'Cohen', 'Steve', 'democrat', 1949, 'Vanderbilt University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-1', 115, 'Gohmert', 'Louie', 'republican', 1953, 'Texas A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-2', 115, 'Crenshaw', 'Dan', 'republican', 1984, 'Tufts University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-3', 115, 'Taylor', 'Van', 'republican', 1972, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-4', 115, 'Ratcliffe', 'John', 'republican', 1965, 'University of Notre Dame');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-5', 115, 'Gooden', 'Lance', 'republican', 1982, 'University of Texas at Austin');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-6', 115, 'Wright', 'Ron', 'republican', 1953, 'University of Texas at Arlington');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-7', 115, 'Fletcher', 'Lizzie Pannill', 'democrat', 1975, 'Kenyon College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-8', 115, 'Brady', 'Kevin', 'republican', 1955, 'University of South Dakota');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-9', 115, 'Green', 'Al', 'democrat', 1947, 'Florida A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-10', 115, 'McCaul', 'Michael', 'republican', 1962, 'Trinity University (Texas)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-11', 115, 'Conaway', 'Mike', 'republican', 1948, 'Texas A&M University–Commerce');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-12', 115, 'Granger', 'Kay', 'republican', 1943, 'Texas Wesleyan University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-13', 115, 'Thornberry', 'Mac', 'republican', 1958, 'Texas Tech University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-14', 115, 'Weber', 'Randy', 'republican', 1953, 'Alvin Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-15', 115, 'González', 'Vicente', 'democrat', 1967, 'Embry–Riddle Aeronautical University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-16', 115, 'Escobar', 'Veronica', 'democrat', 1969, 'University of Texas at El Paso');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-17', 115, 'Flores', 'Bill', 'republican', 1954, 'Texas A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-18', 115, 'Jackson', 'Lee Sheila', 'democrat', 1950, 'Yale University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-19', 115, 'Arrington', 'Jodey', 'republican', 1972, 'Texas Tech University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-20', 115, 'Castro', 'Joaquin', 'democrat', 1974, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-21', 115, 'Roy', 'Chip', 'republican', 1972, 'University of Virginia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-22', 115, 'Olson', 'Pete', 'republican', 1962, 'Rice University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-23', 115, 'Hurd', 'Will', 'republican', 1977, 'Texas A&M University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-24', 115, 'Marchant', 'Kenny', 'republican', 1951, 'Southern Nazarene University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-25', 115, 'Williams', 'Roger', 'republican', 1949, 'Texas Christian University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-26', 115, 'Burgess', 'Michael', 'republican', 1950, 'University of North Texas');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-27', 115, 'Cloud', 'Michael', 'republican', 1975, 'Oral Roberts University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-28', 115, 'Cuellar', 'Henry', 'democrat', 1955, 'Laredo Community College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-29', 115, 'Garcia', 'Sylvia', 'democrat', 1950, 'Texas Womans University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-30', 115, 'Johnson', 'Eddie Bernice', 'democrat', 1935, 'Saint Marys College (Indiana)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-31', 115, 'Carter', 'John', 'republican', 1941, 'Texas Tech University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-32', 115, 'Allred', 'Colin', 'democrat', 1983, 'Baylor University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-33', 115, 'Veasey', 'Marc', 'democrat', 1971, 'Texas Wesleyan University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-34', 115, 'Vela', 'Jr. Filemon', 'democrat', 1963, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-35', 115, 'Doggett', 'Lloyd', 'democrat', 1946, 'University of Texas at Austin');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-TX-36', 115, 'Babin', 'Brian', 'republican', 1948, 'Lamar University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-UT-1', 115, 'Bishop', 'Rob', 'republican', 1951, 'University of Utah');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-UT-2', 115, 'Stewart', 'Chris', 'republican', 1960, 'Utah State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-UT-3', 115, 'Curtis', 'John', 'republican', 1960, 'Brigham Young University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-UT-4', 115, 'McAdams', 'Ben', 'democrat', 1974, 'University of Utah');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VT-AL', 115, 'Welch', 'Peter', 'democrat', 1947, 'College of the Holy Cross');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-1', 115, 'Wittman', 'Rob', 'republican', 1959, 'Virginia Tech');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-2', 115, 'Luria', 'Elaine', 'democrat', 1975, 'United States Naval Academy');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-3', 115, 'Scott', 'Bobby', 'democrat', 1947, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-4', 115, 'McEachin', 'Donald', 'democrat', 1961, 'American University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-5', 115, 'Riggleman', 'Denver', 'republican', 1970, 'Rowan College at Burlington County');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-6', 115, 'Cline', 'Ben', 'republican', 1972, 'Bates College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-7', 115, 'Spanberger', 'Abigail', 'democrat', 1979, 'University of Virginia');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-8', 115, 'Beyer', 'Don', 'democrat', 1950, 'Williams College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-9', 115, 'Griffith', 'Morgan', 'republican', 1958, 'Emory and Henry College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-10', 115, 'Wexton', 'Jennifer', 'democrat', 1968, 'University of Maryland, College Park');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-VA-11', 115, 'Connolly', 'Gerry', 'democrat', 1950, 'Glen Ellyn, Illinois');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-1', 115, 'DelBene', 'Suzan', 'democrat', 1962, 'Reed College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-2', 115, 'Larsen', 'Rick', 'democrat', 1965, 'Pacific Lutheran University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-3', 115, 'Herrera', 'Beutler Jaime', 'republican', 1978, 'Bellevue College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-4', 115, 'Newhouse', 'Dan', 'republican', 1955, 'Washington State University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-5', 115, 'Rodgers', 'Cathy', 'republican', 1969, 'Pensacola Christian College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-6', 115, 'Kilmer', 'Derek', 'democrat', 1974, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-7', 115, 'Jayapal', 'Pramila', 'democrat', 1965, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-8', 115, 'Schrier', 'Kim', 'democrat', 1968, 'University of California, Berkeley');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-9', 115, 'Smith', 'Adam', 'democrat', 1965, 'Western Washington University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WA-10', 115, 'Heck', 'Denny', 'democrat', 1952, 'Evergreen State College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WV-1', 115, 'McKinley', 'David', 'republican', 1947, 'Purdue University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WV-2', 115, 'Mooney', 'Alex', 'republican', 1971, 'Dartmouth College');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WV-3', 115, 'Miller', 'Carol', 'republican', 1950, 'Columbia College (South Carolina)');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-1', 115, 'Steil', 'Bryan', 'republican', 1981, 'Georgetown University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-2', 115, 'Pocan', 'Mark', 'democrat', 1964, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-3', 115, 'Kind', 'Ron', 'democrat', 1963, 'Harvard University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-4', 115, 'Moore', 'Gwen', 'democrat', 1951, 'Marquette University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-5', 115, 'Sensenbrenner', 'Jim', 'republican', 1943, 'Stanford University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-6', 115, 'Grothman', 'Glenn', 'republican', 1955, 'University of Wisconsin–Madison');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WI-8', 115, 'Gallagher', 'Mike', 'republican', 1984, 'Princeton University');
insert into representative(district, congress_number, last, first, party, year_born, education) values('HR-WY-AL', 115, 'Cheney', 'Liz', 'republican', 1966, 'Colorado College');
